(() => {
 const bucket='company-private',types={logo:'โลโก้บริษัท',signature:'ลายเซ็น',certificate:'หนังสือรับรองบริษัท',pp30:'ภ.พ.30',pp20:'ภ.พ.20',other:'เอกสารอื่น ๆ'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const hex=s=>Array.from(new TextEncoder().encode(s),b=>b.toString(16).padStart(2,'0')).join('');
 const filename=name=>{try{return new TextDecoder().decode(Uint8Array.from(name.split('--')[1].split('.')[0].match(/../g),h=>parseInt(h,16)));}catch{return name;}};
 const validate=async(file,type)=>{
  if(!types[type]||!file||!file.size)throw Error('กรุณาเลือกประเภทและไฟล์');
  if(file.size>10485760)throw Error('ไฟล์ต้องมีขนาดไม่เกิน 10 MB');
  if(file.name.length>120)throw Error('ชื่อไฟล์ยาวเกินไป กรุณาย่อให้ไม่เกิน 120 ตัวอักษร');
  const bytes=new Uint8Array(await file.slice(0,8).arrayBuffer());
  const mime=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':String.fromCharCode(...bytes.slice(0,5))==='%PDF-'?'application/pdf':'';
  if(!mime||(['logo','signature'].includes(type)&&mime==='application/pdf'))throw Error('โลโก้/ลายเซ็นใช้ PNG หรือ JPG ส่วนเอกสารใช้ PDF, PNG หรือ JPG');
  return mime;
 };
 const list=async(request,org,type)=>{
  let rows=[],offset=0;for(;;){const batch=await request(`/storage/v1/object/list/${bucket}`,{method:'POST',body:JSON.stringify({prefix:`${org}/${type}`,limit:100,offset,sortBy:{column:'name',order:'asc'}})});if(!Array.isArray(batch))throw Error('โหลดรายการไฟล์ไม่สำเร็จ');if(!batch.length)break;rows.push(...batch.filter(x=>x.id));offset+=batch.length;}
  return rows.map(x=>({...x,type,path:`${org}/${type}/${x.name}`}));
 };
 let urls=[];
 const mount=async(root,{request,org,user,organization,onSaved})=>{
  urls.forEach(URL.revokeObjectURL);urls=[];
  const memberships=await request(`/rest/v1/organization_members?organization_id=eq.${org}&user_id=eq.${user}&select=role&limit=1`),admin=memberships[0]?.role==='admin';
  root.innerHTML=`<style>#company-profile .cp-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}#company-profile .cp-card{padding:24px;min-width:0}#company-profile .cp-wide{grid-column:1/-1}#company-profile .cp-note{color:#718096;font-size:13px;line-height:1.8}#company-profile textarea,#company-profile select{width:100%;padding:12px;border:1px solid #dfe3ea;border-radius:8px;font:inherit}#company-profile .cp-images{display:flex;gap:18px;flex-wrap:wrap}#company-profile .cp-image{flex:1;min-width:180px;background:#f7f9fc;padding:16px;border-radius:12px}#company-profile .cp-image img{height:100px;max-width:100%;object-fit:contain;display:block;margin:12px auto}#company-profile .cp-upload{display:grid;grid-template-columns:1fr 2fr auto;gap:14px;align-items:end}#company-profile .cp-list{overflow:auto}#company-profile td{overflow-wrap:anywhere}#company-profile [data-notice]{white-space:pre-line}main:has(#company-profile.active-page){min-width:0}@media(max-width:1050px){#company-profile .cp-grid,#company-profile .cp-upload{grid-template-columns:1fr}} </style>
  <p class="cp-note">จัดการข้อมูลที่ใช้ในเอกสาร และเก็บไฟล์บริษัทไว้ในที่เดียว</p><div class="cp-grid">
  <article class="panel cp-card"><h3>1. ข้อมูลทั่วไป</h3><p class="cp-note">ข้อมูลส่วนนี้ใช้บนหัวเอกสารขาย</p><form id="company-profile-form"><fieldset ${admin?'':'disabled'} style="border:0;padding:0;margin:0"><label class="field"><span>ชื่อบริษัท *</span><input name="name" required value="${esc(organization.name)}"></label><label class="field"><span>เลขประจำตัวผู้เสียภาษี</span><input name="taxId" inputmode="numeric" maxlength="13" value="${esc(organization.tax_id)}"></label><label class="field"><span>ที่อยู่บริษัท</span><textarea name="address" rows="4">${esc(organization.address)}</textarea></label><label class="field"><span>อัตรา VAT (%)</span><input name="vatRate" type="number" min="0" max="100" step="0.01" required value="${esc(organization.vat_rate??7)}"></label><button class="primary" type="submit">บันทึกข้อมูลบริษัท</button></fieldset><p role="status" data-profile-notice class="cp-note">${admin?'แก้ไขแล้วกดบันทึกข้อมูลบริษัท':'เฉพาะผู้ดูแลแก้ไขข้อมูลบริษัทได้'}</p></form></article>
  <article class="panel cp-card"><h3>2. โลโก้และลายเซ็น</h3><p class="cp-note">ไฟล์ส่วนตัวสำหรับผู้ดูแล • ลายเซ็นไม่ถูกประทับอัตโนมัติ<br>การอัปโหลดเก็บเป็นไฟล์บริษัท ยังไม่เปลี่ยนรูปบนแบบพิมพ์เดิม</p><div class="cp-images"><div class="cp-image"><b>โลโก้บริษัท</b><div data-logo-preview></div></div><div class="cp-image"><b>ลายเซ็น</b><div data-signature-preview></div></div></div></article>
  <article class="panel cp-card cp-wide"><h3>3. แฟ้มเอกสารบริษัท</h3><p class="cp-note">เฉพาะผู้ดูแลเท่านั้นที่อัปโหลดและดาวน์โหลดได้ • PDF / PNG / JPG ไม่เกิน 10 MB ต่อไฟล์ • อัปโหลดใหม่ไม่ทับไฟล์เดิม</p>${admin?`<form data-upload class="cp-upload"><label class="field"><span>ประเภทไฟล์</span><select name="type">${Object.entries(types).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label class="field"><span>เลือกไฟล์</span><input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg" required><small class="cp-note" data-selected>ยังไม่ได้เลือกไฟล์</small></label><button class="primary" type="submit">อัปโหลดไฟล์</button></form><p role="status" data-notice class="cp-note"></p><div style="display:flex;gap:12px;margin-top:20px"><input class="search" type="search" placeholder="ค้นหาชื่อไฟล์" aria-label="ค้นหาเอกสารบริษัท"><button class="ghost" data-refresh>รีเฟรชไฟล์</button></div><div data-files class="cp-list"></div>`:'<p>ไฟล์ทั้งหมดสงวนสิทธิ์เฉพาะผู้ดูแล</p>'}</article></div>`;
  const layout=document.createElement('style');layout.textContent='#company-profile .field{display:block;min-width:0;margin:14px 0}#company-profile .field>span{display:block;font-size:13px;font-weight:600;margin-bottom:7px}#company-profile .field input{width:100%;min-width:0;padding:12px;border:1px solid #dfe3ea;border-radius:8px;font:inherit;background:white}#company-profile fieldset{min-width:0}#company-profile .cp-grid{grid-template-columns:minmax(0,1fr) minmax(0,1fr)}#company-profile .cp-upload{grid-template-columns:minmax(0,1fr) minmax(0,2fr) auto}#company-profile .cp-note a{display:inline-block;margin:8px;padding:8px 12px;border:1px solid #dfe3ea;border-radius:8px}@media(max-width:1050px){#company-profile .cp-grid,#company-profile .cp-upload{grid-template-columns:minmax(0,1fr)}}';root.prepend(layout);
  root.querySelector('form').onsubmit=async e=>{e.preventDefault();if(!admin)return;const form=e.currentTarget,b=form.querySelector('button'),n=root.querySelector('[data-profile-notice]'),data=Object.fromEntries(new FormData(form));if(!data.name.trim()){n.textContent='กรุณาระบุชื่อบริษัท';return;}if(data.taxId&&!/^\d{13}$/.test(data.taxId)){n.textContent='เลขผู้เสียภาษีต้องเป็นตัวเลข 13 หลัก หรือเว้นว่าง';return;}b.disabled=true;n.textContent='กำลังบันทึก…';try{const saved=await request(`/rest/v1/organizations?id=eq.${org}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({name:data.name.trim(),tax_id:data.taxId||null,address:data.address.trim()||null,vat_rate:Number(data.vatRate)})});if(saved?.length!==1)throw Error('ไม่มีสิทธิ์บันทึกข้อมูล');onSaved(saved[0]);n.textContent='✓ บันทึกข้อมูลบริษัทแล้ว';}catch(err){n.textContent=err.message;}finally{b.disabled=false;}};
  if(!admin){root.querySelector('[data-logo-preview]').textContent='เฉพาะผู้ดูแล';root.querySelector('[data-signature-preview]').textContent='เฉพาะผู้ดูแล';return;}
  let rows=[],busy=false;
  const notice=root.querySelector('[data-notice]'),files=root.querySelector('[data-files]');
  const download=async item=>{const blob=await request(`/storage/v1/object/authenticated/${bucket}/${item.path}`,{responseType:'blob'});const url=URL.createObjectURL(blob);urls.push(url);const a=document.createElement('a');a.href=url;a.download=filename(item.name);a.textContent=`บันทึก ${filename(item.name)}`;const open=document.createElement('a');open.href=url;open.target='_blank';open.rel='noopener';open.textContent='เปิดไฟล์';notice.replaceChildren(document.createTextNode('ไฟล์พร้อมแล้ว: '),a,open);};
  const render=()=>{const q=root.querySelector('input[type=search]').value.trim().toLowerCase();const visible=rows.filter(x=>filename(x.name).toLowerCase().includes(q));files.innerHTML=`<table><thead><tr><th>ชื่อไฟล์</th><th>ประเภท</th><th>วันที่อัปโหลด</th><th>ขนาด</th><th>ดาวน์โหลด</th></tr></thead><tbody>${visible.map((x,i)=>`<tr><td>${esc(filename(x.name))}</td><td>${types[x.type]}</td><td>${esc(new Date(x.created_at).toLocaleDateString('th-TH'))}</td><td>${(Number(x.metadata?.size||0)/1024/1024).toFixed(2)} MB</td><td><button type="button" class="ghost" data-download="${i}">ดาวน์โหลด</button></td></tr>`).join('')||'<tr><td colspan="5">ยังไม่มีไฟล์ที่ตรงกับรายการนี้</td></tr>'}</tbody></table>`;files.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await download(visible[Number(b.dataset.download)]);}catch(e){notice.textContent=e.message;}finally{b.disabled=false;}});};
  const refresh=async()=>{files.textContent='กำลังโหลดไฟล์…';try{rows=(await Promise.all(Object.keys(types).map(t=>list(request,org,t)))).flat().sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));render();for(const t of ['logo','signature']){const box=root.querySelector(`[data-${t}-preview]`),item=rows.find(x=>x.type===t);box.replaceChildren();if(!item){box.textContent=t==='logo'?'ยังไม่มีโลโก้ที่อัปโหลด':'ยังไม่มีลายเซ็น';continue;}try{const blob=await request(`/storage/v1/object/authenticated/${bucket}/${item.path}`,{responseType:'blob'});const url=URL.createObjectURL(blob);urls.push(url);const img=document.createElement('img');img.src=url;img.alt=types[t];box.append(img);}catch{box.textContent='โหลดตัวอย่างไม่สำเร็จ กรุณาดาวน์โหลดจากรายการ';}}}catch(e){files.textContent=`โหลดไฟล์ไม่สำเร็จ: ${e.message} กดรีเฟรชเพื่อลองใหม่`;throw e;}};
  root.querySelector('input[type=search]').oninput=render;
  root.querySelector('[data-refresh]').onclick=()=>refresh().catch(e=>notice.textContent=e.message);
  const upload=root.querySelector('[data-upload]');upload.querySelector('input[type=file]').onchange=e=>{const f=e.target.files[0];root.querySelector('[data-selected]').textContent=f?`${f.name} • ${(f.size/1024/1024).toFixed(2)} MB`:'ยังไม่ได้เลือกไฟล์';};
  upload.onsubmit=async e=>{e.preventDefault();if(busy)return;const f=upload.querySelector('input[type=file]').files[0],type=upload.querySelector('select').value;busy=true;const controls=[...upload.querySelectorAll('input,select,button')];controls.forEach(x=>x.disabled=true);let uploaded=false;try{const mime=await validate(f,type),ext=mime==='application/pdf'?'pdf':mime==='image/png'?'png':'jpg',path=`${org}/${type}/${crypto.randomUUID()}--${hex(f.name)}.${ext}`;notice.textContent='กำลังอัปโหลด…';await request(`/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{'Content-Type':mime,'x-upsert':'false'},body:f});uploaded=true;upload.reset();root.querySelector('[data-selected]').textContent='ยังไม่ได้เลือกไฟล์';notice.textContent='✓ อัปโหลดไฟล์แล้ว';await refresh();}catch(err){notice.textContent=uploaded?`อัปโหลดแล้ว แต่โหลดรายการไม่สำเร็จ กรุณารีเฟรช: ${err.message}`:`อัปโหลดไม่สำเร็จหรือยังยืนยันผลไม่ได้: ${err.message} กรุณารีเฟรชตรวจรายการก่อนอัปโหลดซ้ำ`;}finally{busy=false;controls.forEach(x=>x.disabled=false);}};
  await refresh().catch(e=>notice.textContent=e.message);
 };
 window.CompanyProfile={mount,validate,filename,hex,list};
})();
